### ISSUE TITLE
decouple bpm host and bsm host

### ISSUE THREAD

**Issue by arun-hg** [HPSoftware/hubot-bpm#18]
Currently, the host entry configured in bpm-config.json is expected to have both BSM and BPM installed.
The expectation in fix is to have a new (optional) configurable field for BPM host. If this isn't provided, then the bot assumes that the host provided has both BPM and BSM installed.

**Comment by mmishalov** [comment]
any update on this one?

**Comment by arun-hg** [comment]
I am done with the changes. Lets review and merge to master branch today.

**Comment by arun-hg** [comment]
fix reviewed and merged to develop branch. closing the issue.
